import { toCamelCaseFirst } from '../../../functions/string'

import { ComponentsItems } from './ComponentsItems'

import { PropertiesFile } from '../properties/PropertiesFile'

import {
  COMPONENTS_DIR,
  COMPONENTS_MAIN
} from '../../../types/components'

/**
 * Class for working with the main files.<br>
 * Класс для работы с главными файлами.
 */
export class ComponentsMain {
  /**
   * Constructor
   * @param items object for working with the list of components /<br>объект для работы со списком компонентов
   */
  // eslint-disable-next-line no-useless-constructor
  constructor (
    protected readonly items: ComponentsItems
  ) {
  }

  /**
   * Export data for the main file.<br>
   * Экспортировать данные для главного файла.
   */
  make (): this {
    const name = this.items.getGlobalName()

    PropertiesFile.write(
      [COMPONENTS_DIR],
      COMPONENTS_MAIN,
      [
        '// This file is generated by a script, do not edit.',
        '// Этот файл генерируется скриптом, не редактировать.',
        '',
        'import { MutationGlobal } from \'./../classes/mutation/MutationGlobal\'',
        'import { MutationGlobalRef } from \'./../classes/mutation/MutationGlobalRef\'',
        '',
        'import * as functions from \'./../functions/all\'',
        'import * as classes from \'./../classes/all\'',
        'import { components } from \'./components\'',
        '',
        'MutationGlobal.addFunctionList(functions)',
        'MutationGlobal.addClassList(classes)',
        'MutationGlobal.addComponentList(components)',
        '',
        `;(window as any).${name} = MutationGlobal`,
        `;(window as any).${name}_VUE = MutationGlobalRef`,
        '',
        `export { create${toCamelCaseFirst(name)}Components } from './create'`,
        ''
      ].join('\r\n'),
      'ts'
    )

    return this
  }
}
