import { ComponentsItems } from './ComponentsItems.ts'
import { PropertiesFile } from '../properties/PropertiesFile.ts'
import {
  COMPONENTS_DIR,
  COMPONENTS_TYPES
} from '../../../types/components.ts'

export class ComponentsTypes {
  /**
   * Constructor
   * @param items object for working with the list of components /<br>объект для работы со списком компонентов
   */
  // eslint-disable-next-line no-useless-constructor
  constructor (
    protected readonly items: ComponentsItems
  ) {
  }

  make (): this {
    PropertiesFile.write(
      [COMPONENTS_DIR],
      COMPONENTS_TYPES,
      [
        '// This file is generated by a script, do not edit.',
        '// Этот файл генерируется скриптом, не редактировать.',
        '',
        'import \'@vue/runtime-core\'',
        '',
        'import { components } from \'./components.ts\'',
        '',
        'declare module \'@vue/runtime-core\' {',
        '  export interface GlobalComponents {',
        ...this.initComponents(),
        '  }',
        '}',
        ''
      ].join('\r\n'),
      'd.mts'
    )

    return this
  }

  /**
   * Initializes the list of available components.<br>
   * Инициализирует список доступных компонентов.
   */
  protected initComponents (): string[] {
    const data: string[] = []

    this.items
      .getComponentList()
      .forEach(({ codeFull }) => data.push(`    ${codeFull}: typeof components.${codeFull}`))

    return data
  }
}
