// This file is generated by a script, do not edit.
// Этот файл генерируется скриптом, не редактировать.

export const components = {
  M2Icon: import('./../m2/Icon'),
  M2Image: import('./../m2/Image'),
  M2Ripple: import('./../m2/Ripple'),
  M3Button: import('./../m3/Button'),
  M3Checkbox: import('./../m3/Checkbox'),
  M3Chip: import('./../m3/Chip'),
  M3FieldMessage: import('./../m3/FieldMessage'),
  M3Icon: import('./../m3/Icon'),
  M3Image: import('./../m3/Image'),
  M3Input: import('./../m3/Input'),
  M3Mask: import('./../m3/Mask'),
  M3Mutation: import('./../m3/Mutation'),
  M3MutationItem: import('./../m3/MutationItem'),
  M3Progress: import('./../m3/Progress'),
  M3Ripple: import('./../m3/Ripple'),
  M3Scrollbar: import('./../m3/Scrollbar'),
  M3Window: import('./../m3/Window'),
  C1Icon: import('./../c1/Icon'),
  C1Image: import('./../c1/Image'),
  C2Button: import('./../c2/Button'),
  C2Icon: import('./../c2/Icon'),
  C2Image: import('./../c2/Image'),
  C2Mutation: import('./../c2/Mutation'),
  C2MutationItem: import('./../c2/MutationItem'),
  C2Progress: import('./../c2/Progress')
}
