// This file is generated by a script, do not edit.
// Этот файл генерируется скриптом, не редактировать.

import { type Component, createApp } from 'vue'
import { forEach } from '../functions/data.ts'

import { components } from './components.ts'
import './types.d.mts'

export function createUiComponents<A extends Component> (App: A) {
  const app = createApp(App)

  forEach(components, (component, name) => {
    app.component(name, component)
  })

  return app
}
