// This file is generated by a script, do not edit.
// Этот файл генерируется скриптом, не редактировать.

import { type App, type Component, createApp } from 'vue'
import { forEach } from '../functions/data'

import { components } from './components'
import './types.d.ts'

import './../c2/icons.ts'

export function registrationUiComponents (app: App): void {
  forEach(components, (component, name) => {
    app.component(name, component)
  })
}

export function createUiComponents<A extends Component> (App: A) {
  const app = createApp(App)

  registrationUiComponents(app)

  return app
}

export * from './../functions/all'
export * from './../classes/all'
