// This file is generated by a script, do not edit.
// Этот файл генерируется скриптом, не редактировать.

declare module 'ui/M2Icon' {
  export { M2Icon } from 'ui/dist/m2/Icon/index.d.ts'
}
declare module 'ui/M2Image' {
  export { M2Image } from 'ui/dist/m2/Image/index.d.ts'
}
declare module 'ui/M2Ripple' {
  export { M2Ripple } from 'ui/dist/m2/Ripple/index.d.ts'
}
declare module 'ui/M3Button' {
  export { M3Button } from 'ui/dist/m3/Button/index.d.ts'
}
declare module 'ui/M3Checkbox' {
  export { M3Checkbox } from 'ui/dist/m3/Checkbox/index.d.ts'
}
declare module 'ui/M3Chip' {
  export { M3Chip } from 'ui/dist/m3/Chip/index.d.ts'
}
declare module 'ui/M3FieldMessage' {
  export { M3FieldMessage } from 'ui/dist/m3/FieldMessage/index.d.ts'
}
declare module 'ui/M3Icon' {
  export { M3Icon } from 'ui/dist/m3/Icon/index.d.ts'
}
declare module 'ui/M3Image' {
  export { M3Image } from 'ui/dist/m3/Image/index.d.ts'
}
declare module 'ui/M3Input' {
  export { M3Input } from 'ui/dist/m3/Input/index.d.ts'
}
declare module 'ui/M3Mask' {
  export { M3Mask } from 'ui/dist/m3/Mask/index.d.ts'
}
declare module 'ui/M3Progress' {
  export { M3Progress } from 'ui/dist/m3/Progress/index.d.ts'
}
declare module 'ui/M3Ripple' {
  export { M3Ripple } from 'ui/dist/m3/Ripple/index.d.ts'
}
declare module 'ui/M3Scrollbar' {
  export { M3Scrollbar } from 'ui/dist/m3/Scrollbar/index.d.ts'
}
declare module 'ui/M3Window' {
  export { M3Window } from 'ui/dist/m3/Window/index.d.ts'
}
declare module 'ui/C1Icon' {
  export { C1Icon } from 'ui/dist/c1/Icon/index.d.ts'
}
declare module 'ui/C1Image' {
  export { C1Image } from 'ui/dist/c1/Image/index.d.ts'
}
declare module 'ui/C2Button' {
  export { C2Button } from 'ui/dist/c2/Button/index.d.ts'
}
declare module 'ui/C2Icon' {
  export { C2Icon } from 'ui/dist/c2/Icon/index.d.ts'
}
declare module 'ui/C2Image' {
  export { C2Image } from 'ui/dist/c2/Image/index.d.ts'
}
declare module 'ui/C2Progress' {
  export { C2Progress } from 'ui/dist/c2/Progress/index.d.ts'
}
