// This file is generated by a script, do not edit.
// Этот файл генерируется скриптом, не редактировать.

import { Icons } from './../classes/Icons'

import AdSvg from '../media/flags/AD.svg'
import AeSvg from '../media/flags/AE.svg'
import AfSvg from '../media/flags/AF.svg'
import AgSvg from '../media/flags/AG.svg'
import AiSvg from '../media/flags/AI.svg'
import AlSvg from '../media/flags/AL.svg'
import AmSvg from '../media/flags/AM.svg'
import AnSvg from '../media/flags/AN.svg'
import AoSvg from '../media/flags/AO.svg'
import AqSvg from '../media/flags/AQ.svg'
import ArSvg from '../media/flags/AR.svg'
import AsSvg from '../media/flags/AS.svg'
import AtSvg from '../media/flags/AT.svg'
import AuSvg from '../media/flags/AU.svg'
import AwSvg from '../media/flags/AW.svg'
import AxSvg from '../media/flags/AX.svg'
import AzSvg from '../media/flags/AZ.svg'
import BaSvg from '../media/flags/BA.svg'
import BbSvg from '../media/flags/BB.svg'
import BdSvg from '../media/flags/BD.svg'
import BeSvg from '../media/flags/BE.svg'
import BfSvg from '../media/flags/BF.svg'
import BgSvg from '../media/flags/BG.svg'
import BhSvg from '../media/flags/BH.svg'
import BiSvg from '../media/flags/BI.svg'
import BjSvg from '../media/flags/BJ.svg'
import BlSvg from '../media/flags/BL.svg'
import BmSvg from '../media/flags/BM.svg'
import BnSvg from '../media/flags/BN.svg'
import BoSvg from '../media/flags/BO.svg'
import BqSvg from '../media/flags/BQ.svg'
import BrSvg from '../media/flags/BR.svg'
import BsSvg from '../media/flags/BS.svg'
import BtSvg from '../media/flags/BT.svg'
import BvSvg from '../media/flags/BV.svg'
import BwSvg from '../media/flags/BW.svg'
import BySvg from '../media/flags/BY.svg'
import BzSvg from '../media/flags/BZ.svg'
import CaSvg from '../media/flags/CA.svg'
import CcSvg from '../media/flags/CC.svg'
import CdSvg from '../media/flags/CD.svg'
import CfSvg from '../media/flags/CF.svg'
import CgSvg from '../media/flags/CG.svg'
import ChSvg from '../media/flags/CH.svg'
import CiSvg from '../media/flags/CI.svg'
import CkSvg from '../media/flags/CK.svg'
import ClSvg from '../media/flags/CL.svg'
import CmSvg from '../media/flags/CM.svg'
import CnSvg from '../media/flags/CN.svg'
import CoSvg from '../media/flags/CO.svg'
import CrSvg from '../media/flags/CR.svg'
import CuSvg from '../media/flags/CU.svg'
import CvSvg from '../media/flags/CV.svg'
import CwSvg from '../media/flags/CW.svg'
import CxSvg from '../media/flags/CX.svg'
import CySvg from '../media/flags/CY.svg'
import CzSvg from '../media/flags/CZ.svg'
import DeSvg from '../media/flags/DE.svg'
import DjSvg from '../media/flags/DJ.svg'
import DkSvg from '../media/flags/DK.svg'
import DmSvg from '../media/flags/DM.svg'
import DoSvg from '../media/flags/DO.svg'
import DzSvg from '../media/flags/DZ.svg'
import EcSvg from '../media/flags/EC.svg'
import EeSvg from '../media/flags/EE.svg'
import EgSvg from '../media/flags/EG.svg'
import EhSvg from '../media/flags/EH.svg'
import ErSvg from '../media/flags/ER.svg'
import EsSvg from '../media/flags/ES.svg'
import EtSvg from '../media/flags/ET.svg'
import FiSvg from '../media/flags/FI.svg'
import FjSvg from '../media/flags/FJ.svg'
import FkSvg from '../media/flags/FK.svg'
import FmSvg from '../media/flags/FM.svg'
import FoSvg from '../media/flags/FO.svg'
import FrSvg from '../media/flags/FR.svg'
import GaSvg from '../media/flags/GA.svg'
import GbSvg from '../media/flags/GB.svg'
import GdSvg from '../media/flags/GD.svg'
import GeSvg from '../media/flags/GE.svg'
import GfSvg from '../media/flags/GF.svg'
import GgSvg from '../media/flags/GG.svg'
import GhSvg from '../media/flags/GH.svg'
import GiSvg from '../media/flags/GI.svg'
import GlSvg from '../media/flags/GL.svg'
import GmSvg from '../media/flags/GM.svg'
import GnSvg from '../media/flags/GN.svg'
import GpSvg from '../media/flags/GP.svg'
import GqSvg from '../media/flags/GQ.svg'
import GrSvg from '../media/flags/GR.svg'
import GtSvg from '../media/flags/GT.svg'
import GuSvg from '../media/flags/GU.svg'
import GwSvg from '../media/flags/GW.svg'
import GySvg from '../media/flags/GY.svg'
import HkSvg from '../media/flags/HK.svg'
import HmSvg from '../media/flags/HM.svg'
import HnSvg from '../media/flags/HN.svg'
import HrSvg from '../media/flags/HR.svg'
import HtSvg from '../media/flags/HT.svg'
import HuSvg from '../media/flags/HU.svg'
import IdSvg from '../media/flags/ID.svg'
import IeSvg from '../media/flags/IE.svg'
import IlSvg from '../media/flags/IL.svg'
import ImSvg from '../media/flags/IM.svg'
import InSvg from '../media/flags/IN.svg'
import IoSvg from '../media/flags/IO.svg'
import IqSvg from '../media/flags/IQ.svg'
import IrSvg from '../media/flags/IR.svg'
import IsSvg from '../media/flags/IS.svg'
import ItSvg from '../media/flags/IT.svg'
import JeSvg from '../media/flags/JE.svg'
import JmSvg from '../media/flags/JM.svg'
import JoSvg from '../media/flags/JO.svg'
import JpSvg from '../media/flags/JP.svg'
import KeSvg from '../media/flags/KE.svg'
import KgSvg from '../media/flags/KG.svg'
import KhSvg from '../media/flags/KH.svg'
import KiSvg from '../media/flags/KI.svg'
import KmSvg from '../media/flags/KM.svg'
import KnSvg from '../media/flags/KN.svg'
import KpSvg from '../media/flags/KP.svg'
import KrSvg from '../media/flags/KR.svg'
import KwSvg from '../media/flags/KW.svg'
import KySvg from '../media/flags/KY.svg'
import KzSvg from '../media/flags/KZ.svg'
import LaSvg from '../media/flags/LA.svg'
import LbSvg from '../media/flags/LB.svg'
import LcSvg from '../media/flags/LC.svg'
import LiSvg from '../media/flags/LI.svg'
import LkSvg from '../media/flags/LK.svg'
import LrSvg from '../media/flags/LR.svg'
import LsSvg from '../media/flags/LS.svg'
import LtSvg from '../media/flags/LT.svg'
import LuSvg from '../media/flags/LU.svg'
import LvSvg from '../media/flags/LV.svg'
import LySvg from '../media/flags/LY.svg'
import MaSvg from '../media/flags/MA.svg'
import McSvg from '../media/flags/MC.svg'
import MdSvg from '../media/flags/MD.svg'
import MeSvg from '../media/flags/ME.svg'
import MfSvg from '../media/flags/MF.svg'
import MgSvg from '../media/flags/MG.svg'
import MhSvg from '../media/flags/MH.svg'
import MkSvg from '../media/flags/MK.svg'
import MlSvg from '../media/flags/ML.svg'
import MmSvg from '../media/flags/MM.svg'
import MnSvg from '../media/flags/MN.svg'
import MoSvg from '../media/flags/MO.svg'
import MpSvg from '../media/flags/MP.svg'
import MqSvg from '../media/flags/MQ.svg'
import MrSvg from '../media/flags/MR.svg'
import MsSvg from '../media/flags/MS.svg'
import MtSvg from '../media/flags/MT.svg'
import MuSvg from '../media/flags/MU.svg'
import MvSvg from '../media/flags/MV.svg'
import MwSvg from '../media/flags/MW.svg'
import MxSvg from '../media/flags/MX.svg'
import MySvg from '../media/flags/MY.svg'
import MzSvg from '../media/flags/MZ.svg'
import NaSvg from '../media/flags/NA.svg'
import NcSvg from '../media/flags/NC.svg'
import NeSvg from '../media/flags/NE.svg'
import NfSvg from '../media/flags/NF.svg'
import NgSvg from '../media/flags/NG.svg'
import NiSvg from '../media/flags/NI.svg'
import NlSvg from '../media/flags/NL.svg'
import NoSvg from '../media/flags/NO.svg'
import NpSvg from '../media/flags/NP.svg'
import NrSvg from '../media/flags/NR.svg'
import NuSvg from '../media/flags/NU.svg'
import NzSvg from '../media/flags/NZ.svg'
import OmSvg from '../media/flags/OM.svg'
import PaSvg from '../media/flags/PA.svg'
import PeSvg from '../media/flags/PE.svg'
import PfSvg from '../media/flags/PF.svg'
import PgSvg from '../media/flags/PG.svg'
import PhSvg from '../media/flags/PH.svg'
import PkSvg from '../media/flags/PK.svg'
import PlSvg from '../media/flags/PL.svg'
import PmSvg from '../media/flags/PM.svg'
import PnSvg from '../media/flags/PN.svg'
import PrSvg from '../media/flags/PR.svg'
import PsSvg from '../media/flags/PS.svg'
import PtSvg from '../media/flags/PT.svg'
import PwSvg from '../media/flags/PW.svg'
import PySvg from '../media/flags/PY.svg'
import QaSvg from '../media/flags/QA.svg'
import ReSvg from '../media/flags/RE.svg'
import RoSvg from '../media/flags/RO.svg'
import RsSvg from '../media/flags/RS.svg'
import RuSvg from '../media/flags/RU.svg'
import RwSvg from '../media/flags/RW.svg'
import SaSvg from '../media/flags/SA.svg'
import SbSvg from '../media/flags/SB.svg'
import ScSvg from '../media/flags/SC.svg'
import SdSvg from '../media/flags/SD.svg'
import SeSvg from '../media/flags/SE.svg'
import SgSvg from '../media/flags/SG.svg'
import ShSvg from '../media/flags/SH.svg'
import SiSvg from '../media/flags/SI.svg'
import SjSvg from '../media/flags/SJ.svg'
import SkSvg from '../media/flags/SK.svg'
import SlSvg from '../media/flags/SL.svg'
import SmSvg from '../media/flags/SM.svg'
import SnSvg from '../media/flags/SN.svg'
import SoSvg from '../media/flags/SO.svg'
import SrSvg from '../media/flags/SR.svg'
import SsSvg from '../media/flags/SS.svg'
import StSvg from '../media/flags/ST.svg'
import SvSvg from '../media/flags/SV.svg'
import SxSvg from '../media/flags/SX.svg'
import SySvg from '../media/flags/SY.svg'
import SzSvg from '../media/flags/SZ.svg'
import TcSvg from '../media/flags/TC.svg'
import TdSvg from '../media/flags/TD.svg'
import TgSvg from '../media/flags/TG.svg'
import ThSvg from '../media/flags/TH.svg'
import TjSvg from '../media/flags/TJ.svg'
import TkSvg from '../media/flags/TK.svg'
import TlSvg from '../media/flags/TL.svg'
import TmSvg from '../media/flags/TM.svg'
import TnSvg from '../media/flags/TN.svg'
import ToSvg from '../media/flags/TO.svg'
import TrSvg from '../media/flags/TR.svg'
import TtSvg from '../media/flags/TT.svg'
import TvSvg from '../media/flags/TV.svg'
import TwSvg from '../media/flags/TW.svg'
import TzSvg from '../media/flags/TZ.svg'
import UaSvg from '../media/flags/UA.svg'
import UgSvg from '../media/flags/UG.svg'
import UsSvg from '../media/flags/US.svg'
import UySvg from '../media/flags/UY.svg'
import UzSvg from '../media/flags/UZ.svg'
import VaSvg from '../media/flags/VA.svg'
import VcSvg from '../media/flags/VC.svg'
import VeSvg from '../media/flags/VE.svg'
import VgSvg from '../media/flags/VG.svg'
import ViSvg from '../media/flags/VI.svg'
import VnSvg from '../media/flags/VN.svg'
import VuSvg from '../media/flags/VU.svg'
import WfSvg from '../media/flags/WF.svg'
import WsSvg from '../media/flags/WS.svg'
import YeSvg from '../media/flags/YE.svg'
import YtSvg from '../media/flags/YT.svg'
import ZaSvg from '../media/flags/ZA.svg'
import ZmSvg from '../media/flags/ZM.svg'
import ZwSvg from '../media/flags/ZW.svg'

export const makeFlagsGlobal = (): void => {
  Icons.add('flag-ad', AdSvg)
  Icons.add('flag-ae', AeSvg)
  Icons.add('flag-af', AfSvg)
  Icons.add('flag-ag', AgSvg)
  Icons.add('flag-ai', AiSvg)
  Icons.add('flag-al', AlSvg)
  Icons.add('flag-am', AmSvg)
  Icons.add('flag-an', AnSvg)
  Icons.add('flag-ao', AoSvg)
  Icons.add('flag-aq', AqSvg)
  Icons.add('flag-ar', ArSvg)
  Icons.add('flag-as', AsSvg)
  Icons.add('flag-at', AtSvg)
  Icons.add('flag-au', AuSvg)
  Icons.add('flag-aw', AwSvg)
  Icons.add('flag-ax', AxSvg)
  Icons.add('flag-az', AzSvg)
  Icons.add('flag-ba', BaSvg)
  Icons.add('flag-bb', BbSvg)
  Icons.add('flag-bd', BdSvg)
  Icons.add('flag-be', BeSvg)
  Icons.add('flag-bf', BfSvg)
  Icons.add('flag-bg', BgSvg)
  Icons.add('flag-bh', BhSvg)
  Icons.add('flag-bi', BiSvg)
  Icons.add('flag-bj', BjSvg)
  Icons.add('flag-bl', BlSvg)
  Icons.add('flag-bm', BmSvg)
  Icons.add('flag-bn', BnSvg)
  Icons.add('flag-bo', BoSvg)
  Icons.add('flag-bq', BqSvg)
  Icons.add('flag-br', BrSvg)
  Icons.add('flag-bs', BsSvg)
  Icons.add('flag-bt', BtSvg)
  Icons.add('flag-bv', BvSvg)
  Icons.add('flag-bw', BwSvg)
  Icons.add('flag-by', BySvg)
  Icons.add('flag-bz', BzSvg)
  Icons.add('flag-ca', CaSvg)
  Icons.add('flag-cc', CcSvg)
  Icons.add('flag-cd', CdSvg)
  Icons.add('flag-cf', CfSvg)
  Icons.add('flag-cg', CgSvg)
  Icons.add('flag-ch', ChSvg)
  Icons.add('flag-ci', CiSvg)
  Icons.add('flag-ck', CkSvg)
  Icons.add('flag-cl', ClSvg)
  Icons.add('flag-cm', CmSvg)
  Icons.add('flag-cn', CnSvg)
  Icons.add('flag-co', CoSvg)
  Icons.add('flag-cr', CrSvg)
  Icons.add('flag-cu', CuSvg)
  Icons.add('flag-cv', CvSvg)
  Icons.add('flag-cw', CwSvg)
  Icons.add('flag-cx', CxSvg)
  Icons.add('flag-cy', CySvg)
  Icons.add('flag-cz', CzSvg)
  Icons.add('flag-de', DeSvg)
  Icons.add('flag-dj', DjSvg)
  Icons.add('flag-dk', DkSvg)
  Icons.add('flag-dm', DmSvg)
  Icons.add('flag-do', DoSvg)
  Icons.add('flag-dz', DzSvg)
  Icons.add('flag-ec', EcSvg)
  Icons.add('flag-ee', EeSvg)
  Icons.add('flag-eg', EgSvg)
  Icons.add('flag-eh', EhSvg)
  Icons.add('flag-er', ErSvg)
  Icons.add('flag-es', EsSvg)
  Icons.add('flag-et', EtSvg)
  Icons.add('flag-fi', FiSvg)
  Icons.add('flag-fj', FjSvg)
  Icons.add('flag-fk', FkSvg)
  Icons.add('flag-fm', FmSvg)
  Icons.add('flag-fo', FoSvg)
  Icons.add('flag-fr', FrSvg)
  Icons.add('flag-ga', GaSvg)
  Icons.add('flag-gb', GbSvg)
  Icons.add('flag-gd', GdSvg)
  Icons.add('flag-ge', GeSvg)
  Icons.add('flag-gf', GfSvg)
  Icons.add('flag-gg', GgSvg)
  Icons.add('flag-gh', GhSvg)
  Icons.add('flag-gi', GiSvg)
  Icons.add('flag-gl', GlSvg)
  Icons.add('flag-gm', GmSvg)
  Icons.add('flag-gn', GnSvg)
  Icons.add('flag-gp', GpSvg)
  Icons.add('flag-gq', GqSvg)
  Icons.add('flag-gr', GrSvg)
  Icons.add('flag-gt', GtSvg)
  Icons.add('flag-gu', GuSvg)
  Icons.add('flag-gw', GwSvg)
  Icons.add('flag-gy', GySvg)
  Icons.add('flag-hk', HkSvg)
  Icons.add('flag-hm', HmSvg)
  Icons.add('flag-hn', HnSvg)
  Icons.add('flag-hr', HrSvg)
  Icons.add('flag-ht', HtSvg)
  Icons.add('flag-hu', HuSvg)
  Icons.add('flag-id', IdSvg)
  Icons.add('flag-ie', IeSvg)
  Icons.add('flag-il', IlSvg)
  Icons.add('flag-im', ImSvg)
  Icons.add('flag-in', InSvg)
  Icons.add('flag-io', IoSvg)
  Icons.add('flag-iq', IqSvg)
  Icons.add('flag-ir', IrSvg)
  Icons.add('flag-is', IsSvg)
  Icons.add('flag-it', ItSvg)
  Icons.add('flag-je', JeSvg)
  Icons.add('flag-jm', JmSvg)
  Icons.add('flag-jo', JoSvg)
  Icons.add('flag-jp', JpSvg)
  Icons.add('flag-ke', KeSvg)
  Icons.add('flag-kg', KgSvg)
  Icons.add('flag-kh', KhSvg)
  Icons.add('flag-ki', KiSvg)
  Icons.add('flag-km', KmSvg)
  Icons.add('flag-kn', KnSvg)
  Icons.add('flag-kp', KpSvg)
  Icons.add('flag-kr', KrSvg)
  Icons.add('flag-kw', KwSvg)
  Icons.add('flag-ky', KySvg)
  Icons.add('flag-kz', KzSvg)
  Icons.add('flag-la', LaSvg)
  Icons.add('flag-lb', LbSvg)
  Icons.add('flag-lc', LcSvg)
  Icons.add('flag-li', LiSvg)
  Icons.add('flag-lk', LkSvg)
  Icons.add('flag-lr', LrSvg)
  Icons.add('flag-ls', LsSvg)
  Icons.add('flag-lt', LtSvg)
  Icons.add('flag-lu', LuSvg)
  Icons.add('flag-lv', LvSvg)
  Icons.add('flag-ly', LySvg)
  Icons.add('flag-ma', MaSvg)
  Icons.add('flag-mc', McSvg)
  Icons.add('flag-md', MdSvg)
  Icons.add('flag-me', MeSvg)
  Icons.add('flag-mf', MfSvg)
  Icons.add('flag-mg', MgSvg)
  Icons.add('flag-mh', MhSvg)
  Icons.add('flag-mk', MkSvg)
  Icons.add('flag-ml', MlSvg)
  Icons.add('flag-mm', MmSvg)
  Icons.add('flag-mn', MnSvg)
  Icons.add('flag-mo', MoSvg)
  Icons.add('flag-mp', MpSvg)
  Icons.add('flag-mq', MqSvg)
  Icons.add('flag-mr', MrSvg)
  Icons.add('flag-ms', MsSvg)
  Icons.add('flag-mt', MtSvg)
  Icons.add('flag-mu', MuSvg)
  Icons.add('flag-mv', MvSvg)
  Icons.add('flag-mw', MwSvg)
  Icons.add('flag-mx', MxSvg)
  Icons.add('flag-my', MySvg)
  Icons.add('flag-mz', MzSvg)
  Icons.add('flag-na', NaSvg)
  Icons.add('flag-nc', NcSvg)
  Icons.add('flag-ne', NeSvg)
  Icons.add('flag-nf', NfSvg)
  Icons.add('flag-ng', NgSvg)
  Icons.add('flag-ni', NiSvg)
  Icons.add('flag-nl', NlSvg)
  Icons.add('flag-no', NoSvg)
  Icons.add('flag-np', NpSvg)
  Icons.add('flag-nr', NrSvg)
  Icons.add('flag-nu', NuSvg)
  Icons.add('flag-nz', NzSvg)
  Icons.add('flag-om', OmSvg)
  Icons.add('flag-pa', PaSvg)
  Icons.add('flag-pe', PeSvg)
  Icons.add('flag-pf', PfSvg)
  Icons.add('flag-pg', PgSvg)
  Icons.add('flag-ph', PhSvg)
  Icons.add('flag-pk', PkSvg)
  Icons.add('flag-pl', PlSvg)
  Icons.add('flag-pm', PmSvg)
  Icons.add('flag-pn', PnSvg)
  Icons.add('flag-pr', PrSvg)
  Icons.add('flag-ps', PsSvg)
  Icons.add('flag-pt', PtSvg)
  Icons.add('flag-pw', PwSvg)
  Icons.add('flag-py', PySvg)
  Icons.add('flag-qa', QaSvg)
  Icons.add('flag-re', ReSvg)
  Icons.add('flag-ro', RoSvg)
  Icons.add('flag-rs', RsSvg)
  Icons.add('flag-ru', RuSvg)
  Icons.add('flag-rw', RwSvg)
  Icons.add('flag-sa', SaSvg)
  Icons.add('flag-sb', SbSvg)
  Icons.add('flag-sc', ScSvg)
  Icons.add('flag-sd', SdSvg)
  Icons.add('flag-se', SeSvg)
  Icons.add('flag-sg', SgSvg)
  Icons.add('flag-sh', ShSvg)
  Icons.add('flag-si', SiSvg)
  Icons.add('flag-sj', SjSvg)
  Icons.add('flag-sk', SkSvg)
  Icons.add('flag-sl', SlSvg)
  Icons.add('flag-sm', SmSvg)
  Icons.add('flag-sn', SnSvg)
  Icons.add('flag-so', SoSvg)
  Icons.add('flag-sr', SrSvg)
  Icons.add('flag-ss', SsSvg)
  Icons.add('flag-st', StSvg)
  Icons.add('flag-sv', SvSvg)
  Icons.add('flag-sx', SxSvg)
  Icons.add('flag-sy', SySvg)
  Icons.add('flag-sz', SzSvg)
  Icons.add('flag-tc', TcSvg)
  Icons.add('flag-td', TdSvg)
  Icons.add('flag-tg', TgSvg)
  Icons.add('flag-th', ThSvg)
  Icons.add('flag-tj', TjSvg)
  Icons.add('flag-tk', TkSvg)
  Icons.add('flag-tl', TlSvg)
  Icons.add('flag-tm', TmSvg)
  Icons.add('flag-tn', TnSvg)
  Icons.add('flag-to', ToSvg)
  Icons.add('flag-tr', TrSvg)
  Icons.add('flag-tt', TtSvg)
  Icons.add('flag-tv', TvSvg)
  Icons.add('flag-tw', TwSvg)
  Icons.add('flag-tz', TzSvg)
  Icons.add('flag-ua', UaSvg)
  Icons.add('flag-ug', UgSvg)
  Icons.add('flag-us', UsSvg)
  Icons.add('flag-uy', UySvg)
  Icons.add('flag-uz', UzSvg)
  Icons.add('flag-va', VaSvg)
  Icons.add('flag-vc', VcSvg)
  Icons.add('flag-ve', VeSvg)
  Icons.add('flag-vg', VgSvg)
  Icons.add('flag-vi', ViSvg)
  Icons.add('flag-vn', VnSvg)
  Icons.add('flag-vu', VuSvg)
  Icons.add('flag-wf', WfSvg)
  Icons.add('flag-ws', WsSvg)
  Icons.add('flag-ye', YeSvg)
  Icons.add('flag-yt', YtSvg)
  Icons.add('flag-za', ZaSvg)
  Icons.add('flag-zm', ZmSvg)
  Icons.add('flag-zw', ZwSvg)
}
