// This file is generated by a script, do not edit.
// Этот файл генерируется скриптом, не редактировать.

export const makeMediaGlobal = async (): Promise<void> => {
  ;(await import('./../c2/icons.ts')).makeIconsGlobal()
}
