// This file is generated by a script, do not edit.
// Этот файл генерируется скриптом, не редактировать.

import * as components from './components.ts'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    M2Icon: typeof components.M2Icon
    M2Image: typeof components.M2Image
    M2Ripple: typeof components.M2Ripple
    M3Button: typeof components.M3Button
    M3Checkbox: typeof components.M3Checkbox
    M3Chip: typeof components.M3Chip
    M3FieldMessage: typeof components.M3FieldMessage
    M3Icon: typeof components.M3Icon
    M3Image: typeof components.M3Image
    M3Input: typeof components.M3Input
    M3Mask: typeof components.M3Mask
    M3Progress: typeof components.M3Progress
    M3Ripple: typeof components.M3Ripple
    M3Scrollbar: typeof components.M3Scrollbar
    M3Window: typeof components.M3Window
    C1Icon: typeof components.C1Icon
    C1Image: typeof components.C1Image
    C2Button: typeof components.C2Button
    C2Icon: typeof components.C2Icon
    C2Image: typeof components.C2Image
    C2Progress: typeof components.C2Progress
  }
}
