import { ComponentsItems } from './ComponentsItems'
import { PropertiesFile } from '../properties/PropertiesFile'
import {
  COMPONENTS_DIR,
  COMPONENTS_FILE_TYPES
} from '../../../types/components'

export class ComponentsFileTypes {
  /**
   * Constructor
   * @param items object for working with the list of components /<br>объект для работы со списком компонентов
   */
  // eslint-disable-next-line no-useless-constructor
  constructor (
    protected readonly items: ComponentsItems
  ) {
  }

  make (): this {
    PropertiesFile.write(
      [COMPONENTS_DIR],
      COMPONENTS_FILE_TYPES,
      [
        '// This file is generated by a script, do not edit.',
        '// Этот файл генерируется скриптом, не редактировать.',
        '',
        ...this.initComponents(),
        ''
      ].join('\r\n'),
      'd.ts'
    )

    return this
  }

  /**
   * Initializes the list of available components.<br>
   * Инициализирует список доступных компонентов.
   */
  protected initComponents (): string[] {
    const data: string[] = []
    const dirMain: string = this.items.getGlobalName().toLowerCase()

    this.items
      .getComponentList()
      .forEach(({
        design,
        codeFull,
        dir
      }) => {
        data.push(
          `declare module '${dirMain}/${codeFull}' {`,
          `  export { ${codeFull} } from '${dirMain}/dist/${design}/${dir}/index.d.ts'`,
          '}'
        )
      })

    return data
  }
}
